FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y \
    libgdal-dev gcc libgl1 libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*
COPY requirements.worker.txt .
RUN pip install -r requirements.worker.txt
ENV PYTHONPATH=/app:/app/shared
CMD ["rq", "worker", "--url", "redis://redis:6379", "inference"]