FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y libgdal-dev gcc && rm -rf /var/lib/apt/lists/*
COPY requirements.worker.txt .
RUN pip install -r requirements.worker.txt
COPY worker/ .
CMD ["rq", "worker", "--url", "redis://redis:6379", "inference"]